### ISSUE TITLE
Cloudflare challenge updated

### ISSUE THREAD

**Issue by ProGamer13** [codemanki/cloudscraper#199] opened 2019-04-15 10:20 UTC
Challenge updated needed

**Comment by pro-src** [comment] 2019-04-15 23:18
@ProGamer13 can you provide a URL? I don't see any changes...

If you're having trouble, it's probably your headers. See #195
Duplicate of #195

**Comment by rong-00gle** [comment] 2019-04-16 10:08
```
> var cloudscraper = require('cloudscraper');
undefined
> cloudscraper.get('https://bf4db.com/stats', function(error, response, body) {
...   if (error) {
.....     console.log('Error occurred');
.....   } else {
.....     console.log(body, response);
.....   }
... });
Request {
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] },
  _events:
   [Object: null prototype] {
     pipe: [Function],
     error:
      { [Function: bound onceWrapper] listener: [Function: bound processRequestResponse] },
     complete:
      { [Function: bound onceWrapper] listener: [Function: bound processRequestResponse] } },
  _eventsCount: 3,
  _maxListeners: undefined,
  requester:
   { [Function: request]
     get: [Function],
     head: [Function],
     options: [Function],
     post: [Function],
     put: [Function],
     patch: [Function],
     del: [Function],
     delete: [Function],
     jar: [Function],
     cookie: [Function],
     defaults: [Function],
     forever: [Function],
     Request:
      { [Function: Request]
        super_: [Function],
        debug: undefined,
        defaultProxyHeaderWhiteList: [Array],
        defaultProxyHeaderExclusiveList: [Array] },
     initParams: [Function: initParams],
     debug: [Getter/Setter],
     bindCLS: [Function: RP$bindCLS] },
  headers:
   { Connection: 'keep-alive',
     'User-Agent':
      'Mozilla/5.0 (Linux; U; Android 2.2; en-us; Sprint APA9292KT Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',
     'Cache-Control': 'private',
     Accept:
      'application/xml,application/xhtml+xml,text/html;q=0.9, text/plain;q=0.8,image/png,*/*;q=0.5',
     'Accept-Language': 'en-US,en;q=0.9',
     host: 'bf4db.com' },
  cloudflareTimeout: 5000,
  followAllRedirects: true,
  challengesToSolve: 3,
  decodeEmails: false,
  uri:
   Url {
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'bf4db.com',
     port: 443,
     hostname: 'bf4db.com',
     hash: null,
     search: null,
     query: null,
     pathname: '/stats',
     path: '/stats',
     href: 'https://bf4db.com/stats' },
  callback: [Function],
  method: 'GET',
  realEncoding: 'utf8',
  encoding: null,
  readable: true,
  writable: true,
  explicitMethod: true,
  _qs:
   Querystring {
     request: [Circular],
     lib:
      { formats: [Object], parse: [Function], stringify: [Function] },
     useQuerystring: undefined,
     parseOptions: {},
     stringifyOptions: {} },
  _auth:
   Auth {
     request: [Circular],
     hasAuth: false,
     sentAuth: false,
     bearerToken: null,
     user: null,
     pass: null },
  _oauth: OAuth { request: [Circular], params: null },
  _multipart:
   Multipart {
     request: [Circular],
     boundary: '89cee84c-5c7e-4b60-9137-de9357f1c886',
     chunked: false,
     body: null },
  _redirect:
   Redirect {
     request: [Circular],
     followRedirect: true,
     followRedirects: true,
     followAllRedirects: true,
     followOriginalHttpMethod: false,
     allowRedirect: [Function],
     maxRedirects: 10,
     redirects: [],
     redirectsFollowed: 0,
     removeRefererHeader: false },
  _tunnel:
   Tunnel {
     request: [Circular],
     proxyHeaderWhiteList:
      [ 'accept',
        'accept-charset',
        'accept-encoding',
        'accept-language',
        'accept-ranges',
        'cache-control',
        'content-encoding',
        'content-language',
        'content-location',
        'content-md5',
        'content-range',
        'content-type',
        'connection',
        'date',
        'expect',
        'max-forwards',
        'pragma',
        'referer',
        'te',
        'user-agent',
        'via' ],
     proxyHeaderExclusiveList: [] },
  _rp_resolve: [Function],
  _rp_reject: [Function],
  _rp_promise:
   Promise {
     _bitField: 0,
     _fulfillmentHandler0: undefined,
     _rejectionHandler0: undefined,
     _promise0: undefined,
     _receiver0: undefined,
     _onCancelField: [Function] },
  _rp_callbackOrig: [Function],
  _rp_options:
   { requester:
      { [Function: request]
        get: [Function],
        head: [Function],
        options: [Function],
        post: [Function],
        put: [Function],
        patch: [Function],
        del: [Function],
        delete: [Function],
        jar: [Function],
        cookie: [Function],
        defaults: [Function],
        forever: [Function],
        Request: [Function],
        initParams: [Function: initParams],
        debug: [Getter/Setter],
        bindCLS: [Function: RP$bindCLS] },
     jar: RequestJar { _jar: [CookieJar] },
     headers:
      { Connection: 'keep-alive',
        'User-Agent':
         'Mozilla/5.0 (Linux; U; Android 2.2; en-us; Sprint APA9292KT Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',
        'Cache-Control': 'private',
        Accept:
         'application/xml,application/xhtml+xml,text/html;q=0.9, text/plain;q=0.8,image/png,*/*;q=0.5',
        'Accept-Language': 'en-US,en;q=0.9' },
     cloudflareTimeout: 5000,
     followAllRedirects: true,
     challengesToSolve: 3,
     decodeEmails: false,
     uri: 'https://bf4db.com/stats',
     callback: [Function: RP$callback],
     method: 'GET',
     realEncoding: 'utf8',
     encoding: null,
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  setHeader: [Function],
  hasHeader: [Function],
  getHeader: [Function],
  removeHeader: [Function],
  localAddress: undefined,
  pool: {},
  dests: [],
  __isRequestRequest: true,
  _callback: [Function: RP$callback],
  proxy: null,
  tunnel: true,
  setHost: true,
  originalCookieHeader: undefined,
  _jar:
   RequestJar {
     _jar: CookieJar { enableLooseMode: true, store: { idx: {} } } },
  port: 443,
  host: 'bf4db.com',
  path: '/stats',
  httpModule:
   { Agent: { [Function: Agent] super_: [Function] },
     globalAgent:
      Agent {
        domain: [Domain],
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     Server: { [Function: Server] super_: [Function] },
     createServer: [Function: createServer],
     get: [Function: get],
     request: [Function: request] },
  agentClass:
   { [Function: Agent]
     super_:
      { [Function: Agent] super_: [Function], defaultMaxSockets: Infinity } },
  agent:
   Agent {
     domain:
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        members: [] },
     _events: [Object: null prototype] { free: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     defaultPort: 443,
     protocol: 'https:',
     options: { path: null },
     requests: {},
     sockets: {},
     freeSockets: {},
     keepAliveMsecs: 1000,
     keepAlive: false,
     maxSockets: Infinity,
     maxFreeSockets: 256,
     maxCachedSessions: 100,
     _sessionCache: { map: {}, list: [] } },
  cloudscraper: true }
> Error occurred
Unhandled rejection ParserError: 
### Cloudflare may have changed their technique, or there may be a bug.
### Bug Reports: https://github.com/codemanki/cloudscraper/issues
### Check the detailed exception message that follows for the cause.

SyntaxError: Challenge evaluation failed: Unexpected token |
    at solveChallenge (/home/user/node_modules/cloudscraper/index.js:294:21)
    at processRequestResponse (/home/user/node_modules/cloudscraper/index.js:188:12)
    at Object.onceWrapper (events.js:277:13)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:459:23)
    at Request.<anonymous> (/home/user/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:459:23)
    at IncomingMessage.<anonymous> (/home/user/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:459:23)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

> 
```

**Comment by pro-src** [comment] 2019-04-16 10:11
Cloudscraper version?

You should probably update to the latest version.

**Comment by pro-src** [comment] 2019-04-16 10:13
@rong-00gle It's a duplicate of #192 and it's already been fixed. Please update. Thanks

**Comment by rong-00gle** [comment] 2019-04-16 10:19
@pro-src yes you right, Latest version worked fine no error.
And thanks for quick response.

**Comment by pro-src** [comment] 2019-04-16 10:20
You're welcome :smile:

**Closed** 2019-04-18 07:27 UTC
