### ISSUE TITLE
How to set cookies

### ISSUE THREAD

**Issue by lidorlevi156** [codemanki/cloudscraper#207] opened 2019-04-26 02:26 UTC
Its not bypassing for me Cloudflare 5 seconds, i dont know why i use this code:
```
  var options = {
    method: 'GET',
    url:'http://someurl/',
    proxy: 'http://' + proxies[proxy]
  };
  cloudscraper(options).then(console.log);
```
in loop and it drag a lot of errors and some success, but most errors, its not even waiting 5 seconds its log the error on the console in one second.

**Comment by pro-src** [comment] 2019-04-26 06:31
Hi @lidorlevi156, I can't really tell what the problem is based on the information you've provided. For all I know, something is wrong in your code. For example if your `proxies` variable was undefined at some point, that could match what you've described.

If I'm assuming it's not a bug in your code, I still need to know the error message(s), preferably the URL(s), and/or the response content.

Regarding *"waiting 5 seconds"*, there is not any need to wait 5 seconds before reporting a CAPTCHA, etc. In a lot of cases, these errors are valid and meant to be handled by the user.

I'd like to help you find a solution. *Please provide more information.*

**Comment by lidorlevi156** [comment] 2019-04-26 15:13
Hello @pro-src , its saying error: captcha always, in everysite that i try to attack that have 5SEC its throw errors. No matter which site, this is problem I am sure and my proxies working well and not undefined.
There is are errors:

> { errorType: 1 }
> { errorType: 3,
>   error: 'Error occurred during evaluation: Illegal return statement' }

one time type 1, other time 3 and 'Error occurred during evaluation: Illegal return statement'
How should I fix it?

Thank you very much :)

**Comment by lidorlevi156** [comment] 2019-04-26 15:26
Update: On some sites when I send requests to "HTTP" and not to "HTTPS" its bypassing the 5 seconds in some requests, on other part of sites its doesn't.

**Comment by pro-src** [comment] 2019-04-27 01:17
@lidorlevi156 some site owners may have CAPTCHA turned on for specific paths. I'm unable to reproduce this without a URL but the error doesn't seem quite right. Are you using the latest version of Cloudscraper `^4.0.0`??? Based on what you're telling me, I don't think this is a problem with Cloudscraper since to the best of my knowledge Cloudflare has *not* updated their challenge. I doubled checked before replying...

I recommend that you remove `node_modules`, reinstall, and log the version, `console.log(require('cloudscraper/package.json').version)`.

Also see #208 where somebody else mistakenly thought that CF had updated their.

**Comment by pro-src** [comment] 2019-04-27 03:14
@lidorlevi156 if you haven't already, test your proxy in a web browser. It's possible that the proxy server is using SSL ciphers that aren't common to web browsers: https://github.com/VeNoMouS/cloudflare-scrape-js2py/issues/28#issuecomment-487000582

Since the proxy is making the connection to Cloudflare on your behalf... If you get a response, that doesn't rule out the proxy for being a possible cause.

The proxy could...
* change the order of the headers when using plain HTTP.
* add additional headers when using plain HTTP.
* remove headers when using plain HTTP.
* etc...

Does it work when not using a proxy?
Does it work in the web browser when the web browser is configured to use the proxy?
Did you check to see that the browser was actually using the proxy (IP check)?
Etc. Etc....

**Comment by pro-src** [comment] 2019-04-29 00:38
Cloudscraper uses https://www.npmjs.com/package/request which in turn uses https://www.npmjs.com/package/tough-cookie for cookie management. You'll need to refer to the documentation of those respective libraries.

You can access the cookie jar from the defaults: `cloudscraper.defaultParams.jar`
Or use your own:
```js
var tough = require('tough-cookie');
var cookiejar = new tough();
var cloudscraper = require('cloudscraper').defaults({ jar: cookiejar });
```
Or equivalently:
```js
var cloudscraper = require('cloudscraper');
var jar = cloudscraper.jar();
cloudscraper.defaultParams.jar = jar;
```
Or use request's convenience function directly and optionally use request as the requester: 
```js
var request = require('request');
var cloudscraper = require('cloudscraper').defaults({ requester: request, jar: request.jar() });
```

Since this issue has been answered, you should close it. (You can still comment...) But this is not a general support forum. If you have a different question, open a new issue. :smile: 

Good luck!

**Comment by pro-src** [comment] 2019-04-29 00:46
@codemanki Do you mind changing the title of this issue to `How to set cookies`. I'd really appreciate having commit access so I'd be able to manage a bit more on my own. None of the issues have labels and be tend to ask the same question over an over again. We could save everybody some time but fixing this issues up when it makes sense to do so... For example which issues were bugs? So many duplicate titles.

**Comment by codemanki** [comment] 2019-04-29 06:35
@pro-src done. Please accept the invite :)

**Closed** 2019-04-29 07:11 UTC
Labels: question

**Comment by codemanki** [comment] 2019-04-29 07:15
>pro-src closed this 3 minutes ago

![](https://images-na.ssl-images-amazon.com/images/I/61M2ajmsJeL._UL1125_.jpg)
