### ISSUE TITLE
[Bug] Unhandled rejection with callbacks (no promise)

### ISSUE THREAD

**Issue by Revadike** [codemanki/cloudscraper#194] opened 2019-04-13 01:09 UTC
If you use the callback methods, so not the promise way, when getting an error (first parameter of callback) a Unhandled rejection message is still being logged. This seems like unintended behavior.

**Comment by Revadike** [comment] 2019-04-13 01:16
For example:
```
Unhandled rejection CloudflareError: 200, OK
    at processRequestResponse (node_modules\cloudscraper\index.js:174:21)
    at Object.onceWrapper (events.js:285:13)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (node_modules\cloudscraper\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (node_modules\cloudscraper\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```
and
```
Unhandled rejection RequestError: null
    at processRequestResponse (node_modules\cloudscraper\index.js:156:21)
    at Object.onceWrapper (events.js:285:13)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (node_modules\cloudscraper\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (node_modules\cloudscraper\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**Comment by pro-src** [comment] 2019-04-13 01:26
Maybe you should open these issues at https://github.com/request/request or https://github.com/request/request-promise since that is where this behavior is coming from.

If you don't want to use request-promise then use a different `requester`.
```js
const requester = require('request');
const cloudscraper = require('cloudscraper').defaults({ requester });
```

Feel free to close this issue. It's not a bug.

**Comment by pro-src** [comment] 2019-04-13 01:27
@Revadike This is covered in the examples as well...

**Comment by Revadike** [comment] 2019-04-13 03:50
If callback is set, you need to catch any errors and call the callback with that error.

**Comment by pro-src** [comment] 2019-04-13 08:58
Tell https://github.com/request/request-promise your opinion. Or if you don't want to use request-promise... Don't use request-promise :+1:

**Comment by pro-src** [comment] 2019-04-13 09:00
If you want to send a PR, feel free to do so but like I said, it's not a bug.

**Comment by Revadike** [comment] 2019-04-13 15:40
It has nothing to do with `request-promise`. This uncaught exception is on you.

I've taken a look at the source code, but it's very strange to me. It's really non-traditional JavaScript, at least what I am used to. Your code structure and style is very unique to other node.js projects I've seen. Like, why use listeners/observers with `request-promise`? Doesn't that defeat the whole purpose of the promise feature? Anyway, those things striked me as odd and made understanding the code a little hard.

I've added a line of code that made this bug go away by catching it into an empty function, but ideally you want to catch a promise's error and handle it. Sent a pull request: https://github.com/codemanki/cloudscraper/pull/197

**Comment by pro-src** [comment] 2019-04-13 20:16
@Revadike said:
> It has nothing to do with request-promise. This uncaught exception is on you.

You have no idea what you're talking about. I've read the request and request/core and request/promise code-base many times over. Actually try running the following in a shell.
```js
var rp = require('request-promise');
rp.get('https://pro-src.com', () => {});
```
> I've taken a look at the source code, but it's very strange to me. It's really non-traditional JavaScript, at least what I am used to. 

The coding style is literally standard with semicolons (No standardjs is not a standard) but you really haven't looked at any JS projects now have you? Or is it that you don't recognize es5 when you see it?

> Your code structure and style is very unique to other node.js projects I've seen. Like, why use listeners/observers with request-promise?

I kept the original code structure when I rewrote the library. There nothing wrong with it. I don't see your PRs anywhere. The codebase is so small if you actually where looking at the code, why would you ever need to ask a question? Oh wait that goes back to your first accusation. You don't know anything about request or request-promise.

Look, if you're ignorant of the libraries that are being used by this project and how they work internally, they are opensource so go get educated. 

> I've added a line of code that made this bug go away by catching it into an empty function, but ideally you want to catch a promise's error and handle it. Sent a pull request: #197

You're PR doesn't make any sense at all. See those failed tests??? You broke it. This is something that you should fix in your own code sense you lack the coding ability to send a working PR of which isn't needed because this isn't a bug. I already showed you a better way of fixing it.

I'm not trying to stop you from sharing your opinions but when ***you*** use an accusatory tone and have no idea what you're talking about, it is annoying... Stop making things personal. If you'd ask more specific questions without all of that nonsense, I'll answer them for you.

**Comment by pro-src** [comment] 2019-04-13 20:23
I want to add that this library has more code comments per line of code then any other project you're bound to be reading... If that doesn't say it all. :rofl:

**Comment by pro-src** [comment] 2019-04-13 20:36
@codemanki If you'd close this issue since this guy isn't responding well to common sense. Thanks.

**Comment by Revadike** [comment] 2019-04-13 21:48
Okay... I think there was some miscommunication.

I didn't mean to attack you at all. I was simply explaining why it was hard for me to understand what was going on in the source code. I never claimed to be an expert.

Furthermore, I was curious on how some things were done in the source code. Like the example I gave about using listeners/observers for promises.

The pull request broke nothing, it only didn't pass some linter rules (style checker), but it was quickly fixed in the 2nd commit. It was tested and working fine here.

**Comment by pro-src** [comment] 2019-04-13 22:54
@Revadike Sure, I'll accept that.

The addition of that `catch` makes it impossible to catch errors and thus breaks the promise implementation itself.

If you were to try it with the code that your using to solve CAPTCHA's, you would see that it did indeed break your code. Tests are broken because they can't test whether or not was an error, etc... It's broken.

**Comment by pro-src** [comment] 2019-04-13 23:05
@Revadike In regards to your question about listeners. `request-promise` is a very thin wrapper around `request`. It hooks the `init` method of the `Request` class by monkey patching `Request.prototype.init`. The reason we're using listeners is because that is exactly how `request` will callback. The `request.callback` is a result of passing `options.callback` to a `request` call. The same callback is registered as an event listener on the `Request` instance. All request instances whether they are returned from `request`, `request-promise`, or `cloudscraper` are all instance of the `EventEmitter` class. In order to prevent other callbacks from being called, namely the one added by `request-promise` we replace those listeners with are own so that we may prepare the response for you or solve challenges, etc..

**Comment by pro-src** [comment] 2019-04-13 23:10
What would happen if we didn't prevent `request-promise` from handling the response early? By default if the HTTP status code is not in the 2xx range, RP will throw an exception. RP would call the user provided callback instead of cloudscraper, etc. etc.. There are a bunch of gotchas. Anyways, this was the cleanest method of processing the response and controlling callback behavior.

**Comment by pro-src** [comment] 2019-04-13 23:21
@Revadike If you'd like to continue this discussion, I would rename the issue to remove `Bug` and `(no promise)`. I keep saying that it's not a bug. It could be called an issue with documentation, feature-bug, or whatever but labeling it simply as a bug is not accurate. Secondly, cloudscraper always returns a promise when the requester is `request-promise`. As I've mentioned, it is preferable to use `request` as the requester and not `request-promise` if you don't intend on using promises.

**Comment by pro-src** [comment] 2019-04-13 23:37
Food for thought... Why can't you use the built-in feature of Github issues to label this as a bug???? The repository owner and/or those with commit access can but others aren't allowed. Why? You could argue that with Github if you wanted. I agree with their reasoning.

**Comment by codemanki** [comment] 2019-04-18 07:28
Shall i close this or you guys want to continue discussing it?

**Comment by pro-src** [comment] 2019-04-18 07:31
It can be closed.

**Closed** 2019-04-18 07:36 UTC
