### ISSUE TITLE
Error occurred during evaluation: Unexpected string

### ISSUE THREAD

**Issue by kopertop** [codemanki/cloudscraper#21] opened 2016-06-09 15:46 UTC
I'm seeing the error message "Error occurred during evaluation: Unexpected string" while trying to scrape this: http://zolmax.com/feed

**Comment by codemanki** [comment] 2016-06-09 16:08
Closing as duplicate of https://github.com/codemanki/cloudscraper/issues/20

**Closed by codemanki** 2016-06-09 16:08 UTC

**Comment by codemanki** [comment] 2016-06-09 17:53
1.3.0 version has been released.
