### ISSUE TITLE
[Bug] HEAD method

### ISSUE THREAD

**Issue by Revadike** [codemanki/cloudscraper#177] opened 2019-04-02 17:36 UTC
It returns `200, OK` as error with this rejection:
```
Unhandled rejection CloudflareError: 200, OK
    at processRequestResponse (cloudscraper\index.js:174:21)
    at Object.onceWrapper (events.js:285:13)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (cloudscraper\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (cloudscraper\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)```

**Comment by codemanki** [comment] 2019-04-02 18:06
👀 looking into this

**Comment by pro-src** [comment] 2019-04-03 00:01
@Revadike Thats not a bug. You're performing a HEAD request on a Cloudflare protected site. How could we bypass a challenge when the response doesn't contain a body (It's a HEAD request) and doesn't contain a challenge? The reason you got the error is because it sent a challenge. You need to bypass at least one challenge before sending such a request and I don't know why you would want to. However, we could make this error more descriptive, I guess.

**Comment by pro-src** [comment] 2019-04-03 00:11
To be clear, even with the prerequisite headers/cookies, there is no way of knowing whether or not a challenge would've been sent because of this request type. However, what we can do is determine whether or not it's a cloudflare response and narrow it down to being either a server error or challenge. We're already doing that and thus the error. There isn't much we can do to improve this besides changing the error message to be more descriptive. I hope that's clear enough.

**Comment by pro-src** [comment] 2019-04-03 00:47
Sorry, I still don't thing I've been clear enough :smile: 

You were sent headers from Cloudflare and not the server that is being protected by Cloudflare.

**Comment by codemanki** [comment] 2019-04-03 07:41
@pro-src what would you suggest to do in this case then? Catch this specific case and add some description to the error? Or rather update docs explaining why doing Head/Options requests won't work as first requests to a protected website?

**Comment by pro-src** [comment] 2019-04-03 07:54
If we only throw an error, there is no guarantee that they will get this error during testing. If we only add it to the README, they might overlook it. At least if the error is descriptive, they'll know what went wrong so I suggest the former or both. I've been trying to think of a better way of handling this but I've got nothing.

**Comment by pro-src** [comment] 2019-04-03 08:28
@codemanki I think we can improve code readability and that stack trace by separating `processRequestResponse` into two functions: `onRequestResponse` and `onCloudflareResponse`
The former would call the latter if it's a Cloudflare response.

**Comment by Revadike** [comment] 2019-04-03 10:42
to clarify: The website I am trying to reach is (I think) not cloudflare protected, but I am only using cloudscraper as request substitute (it should be able to replace node-request right?)
I am performing a HEAD method to get the redirect URL.

**Comment by pro-src** [comment] 2019-04-03 10:44
@Revadike What version of cloudscraper are you using?

**Comment by pro-src** [comment] 2019-04-03 10:58
> it should be able to replace node-request right?)

For the most part, yes but there is an issue with streams.

> I am performing a HEAD method to get the redirect URL.

```js
const cloudscraper = require('cloudscraper').defaults({ resolveWithFullResponse: true });
const { CloudflareError } = require('cloudscraper/errors');
const { URL } = require('url');

const uri = new URL('https://example-site.dev/path/to/resource');
cloudscraper.head({ uri: uri.href })
  .catch(error => {
    if (error instanceof CloudflareError && error.errorType === 2) {
      return cloudscraper.get({ uri: uri.origin }).then(() => {
        return cloudscraper.head({ uri: uri.href });
      });
    }
  })
  .then(getHeaders)
```

If the response contains a server header that is /^cloudflare/i without a body, you'll get that error.

**Comment by pro-src** [comment] 2019-04-03 11:08
@codemanki I guess we could automatically retry on HEAD requests like I've done in the snippet above. Maybe add a flag? `cloudscraper.defaults({ retry: ['head', 'get'] })` It could potentially bypass some header issues since Cloudflare isn't as strict after the cookie is set.

**Comment by VeNoMouS** [comment] 2019-04-03 12:31
re streams... doesn't stream being "keep-alive"?

**Comment by pro-src** [comment] 2019-04-03 12:50
I'm not aware of any such breakage. I'm primarily talking about node's streams which don't have to be socket or file related.

**Comment by pro-src** [comment] 2019-04-03 13:00
@Revadike Just to make sure that I'm not over looking something, do you mind sharing the response headers?
```js
cloudscraper.debug = true;
```

**Comment by VeNoMouS** [comment] 2019-04-03 13:07
@pro-src ah... anyway i was refering to this https://en.wikipedia.org/wiki/HTTP_persistent_connection#Keepalive_with_chunked_transfer_encoding

```
Keepalive with chunked transfer encoding
Keepalive makes it difficult for the client to determine where one response ends and the next response begins, particularly during pipelined HTTP operation.[8] This is a serious problem when Content-Length cannot be used due to streaming.[9] To solve this problem, HTTP 1.1 introduced a chunked transfer coding that defines a last-chunk bit.[10] The last-chunk bit is set at the end of each response so that the client knows where the next response begins.```

**Comment by pro-src** [comment] 2019-04-05 01:40
@codemanki The issue I just linked is practically the same as this one but for cloudflare-scrape-js2py. What do you think about adding options: `{ retry: ['head', 'get'], retries: 1 }`. The user would specify which HTTP verbs we should retry on. A retry would consist of making a GET request on behalf of the user before retrying the original request and resolving with the result. We'd only ever retry if the user has included the options(s) and when the response is a challenge but the HTTP verb isn't GET. If you're in favor of this feature, I'll add that we'd want to detect whether or not a challenge was bypassed before actually retrying the original request to avoid overhead/loops.

**Comment by VeNoMouS** [comment] 2019-04-05 01:42
Yea I think thats a good idea.

**Comment by pro-src** [comment] 2019-04-05 16:48
@Revadike 
If the server is for some reason sending response headers that match `/^cloudflare/i.test(headers["Server"])`, I would just ignore the error.

```js
const headers = await cloudscraper.head({ uri, resolveWithFullResponse: true })
  .catch(error => {
    if (error.errorType === 2) {
      return error.response.headers;
    }
    throw error;
  })
  .then(response => response.headers);
```

I think this issue can be closed.

**Closed** 2019-04-07 08:56 UTC

**Comment by Revadike** [comment] 2019-04-13 01:19
Adding an exception for error.errorType === 2 works but I find that a dirty solution. Is there no better way to not throw an error when using HEAD method?

**Comment by pro-src** [comment] 2019-04-13 09:30
@Revadike we can take the same approach that @VeNoMouS took and send an additional request for you but no not really.

**Comment by pro-src** [comment] 2019-04-13 09:34
Basically we'd just catch that particular error, send a regular GET request for you then resend your HEAD request but that's only one verb where this particular issue is encountered. The same can happen for POST, OPTIONS, DELETE, etc.. I've been considering but I think it's just a more convenient dirty solution that could have some bad consequences if you're not aware of it.
