### ISSUE TITLE
how to download binary files

### ISSUE THREAD

**Issue by grasssnake123** [codemanki/cloudscraper#181] opened 2019-04-03 12:22 UTC
how to download binary files and store it in local machine.
code:
`var cloudscraper = require('cloudscraper');
var fs = require('fs');
cloudscraper.get({ uri: 'https://subscene.com/content/images/logo.gif', encoding: null }).then(bufferAsBody => fs.writeFileSync('./image.gif', bufferAsBody));`

i keep getting this error:

> Unhandled rejection ParserError:
> ### Cloudflare may have changed their technique, or there may be a bug.
> ### Bug Reports: https://github.com/codemanki/cloudscraper/issues
> ### Check the detailed exception message that follows for the cause.
> 
> TypeError: Challenge evaluation failed: g is not a function
>     at solveChallenge (/../nodejs/node_modules/cloudscraper/index.js:294:21)
>     at processRequestResponse (/../nodejs/node_modules/cloudscraper/index.js:188:12)
>     at Object.onceWrapper (events.js:281:20)
>     at Request.emit (events.js:193:13)
>     at Request.<anonymous> (/../nodejs/node_modules/request/request.js:1161:10)
>     at Request.emit (events.js:193:13)
>     at IncomingMessage.<anonymous> (/../nodejs/node_modules/request/request.js:1083:12)
>     at Object.onceWrapper (events.js:281:20)
>     at IncomingMessage.emit (events.js:198:15)
>     at endReadableNT (_stream_readable.js:1142:12)
>     at processTicksAndRejections (internal/process/task_queues.js:81:17)
>

**Comment by pro-src** [comment] 2019-04-03 12:34
Duplicate of #179

**Comment by pro-src** [comment] 2019-04-03 21:32
@grasssnake123 Do you mind closing this issue. codemanki and I are playing wack-a-mole with issues lately because Cloudflare has been updating more frequently than ever before.

**Comment by pro-src** [comment] 2019-04-03 23:55
Examples: https://github.com/codemanki/cloudscraper/pull/182/files

**Closed** 2019-04-04 04:13 UTC
