### ISSUE TITLE
Today get error

### ISSUE THREAD

**Issue by Anarcht** [codemanki/cloudscraper#173] opened 2019-03-30 23:03 UTC
Hi, these days it has been working perfectly, but this afternoon, it has given this error:

I know perfectly that it does not solve captchas, but the page does not have the captcha activated, I have tried it from different ip, browsers, mobile. 
Page is activated DDoS protection by Cloudflare 5 secs

`Unhandled rejection CaptchaError: captcha
    at validate (/volume1/homes/admin/node_modules/cloudscraper/index.js:193:11)
    at processRequestResponse (/volume1/homes/admin/node_modules/cloudscraper/index.js:161:5)
    at Object.onceWrapper (events.js:272:13)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/volume1/homes/admin/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/volume1/homes/admin/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)`

It has failed without change the code

node version v9.11.1

I write here if you have changed something in the cloudflare that you should know.

Thanks, greetings.

**Comment by pro-src** [comment] 2019-03-30 23:42
Cloudscraper version?

I think this is a duplicate of #170 and we should have a fix for it soon.

**Comment by Anarcht** [comment] 2019-03-30 23:49
Last version install for npm: 3.4.0

Few minutes ago, i try a clean installation, but I have the same error.

> I think this is a duplicate of #170 and we should have a fix for it soon.

Ok!! Very thanks.

**Comment by pro-src** [comment] 2019-03-31 01:21
@Anarcht can you provide a URL where Cloudscraper fails for testing purposes? I have a fix but I haven't been able to confirm it.

Also, if you'd like to test the fix:
```sh
cd your-project
npm i --save "git://github.com/pro-src/cloudscraper.git#170_fix_build"
# The following command will remove node_modules and do a fresh install 
npm ci
```

**Comment by Anarcht** [comment] 2019-03-31 03:07
I have placed the command as you have written to me, and it has been updated.
Unfortunately, to try we'll have to wait a few hours, because as I said in the first post, when the web has a high load, it is when activate the DDoS protection by Cloudflare 5 secs

We will wait about 10 hours or hopefully something less.

I will tell you, thank you very much.
Greetings.

**Comment by pro-src** [comment] 2019-03-31 09:09
@Anarcht I've confirmed the fix in #174 but you'll want to re-run those commands before testing it. There will be a new release soon anyways so no worries :+1:

**Closed** 2019-03-31 10:34 UTC

**Comment by codemanki** [comment] 2019-03-31 11:30
@Anarcht `3.5.0` was released. Thanks @pro-src for adjusting the challenge solver!

**Comment by Anarcht** [comment] 2019-03-31 12:34
@codemanki Installed 3.5.0, very thanks to @pro-src and you for work!!
